questions/urls.py
from django.conf.urls import url
from django.contrib import auth
from django.template.backends import django

from . import views

app_name = 'questions'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^question_form/$', views.question_form, name='question_form'),
    url(r'^new_question/$', views.new_question, name='new_question'),
    url(r'^question_answers/(?P<question_id>[0-9]+)/$', views.question_answers, name='question_answers'),
    url(r'^add_question_answer/(?P<question_id>[0-9]+)/$', views.add_question_answer, name='add_question_answer'),
    url(r'^vote_question/(?P<question_id>[0-9]+)/$', views.vote_question, name='vote_question'),
    url(r'^vote_answer/(?P<question_id>[0-9]+)/$', views.vote_answer, name='vote_answer'),
    url(r'^change/password/$',views.change_password, name='changepassword'),
    url(r'^users/add$', views.add_user, name='add_user')
]

stackoverflow/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views



urlpatterns = [
    url(r'', include('questions.urls')),
    url(r'^questions/', include('questions.urls')),
    url(r'^admin/', admin.site.urls),
    # url(r'^login/$', auth_views.login, {'template_name': 'questions/login.html', 'authentication_form': LoginForm}, name='login'),
    url(r'^login/$', auth_views.login, {'template_name': 'questions/login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': 'questions:index'}, name='logout'),

    url(r'^reset/password_reset/$', auth_views.password_reset, name='reset_password_reset1'),
    url(r'^reset/password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete')




]

questions/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.

class Category(models.Model):
    category_name = models.CharField(max_length=5)
    category_desc = models.CharField(max_length=50)

    def __str__(self):
        return self.category_name + ' : ' + self.category_desc


class Question(models.Model):
    question_title = models.CharField(max_length=200, default='')
    question_text = models.CharField(max_length=1000)
    views = models.IntegerField(default=0)
    votes = models.IntegerField(default=0)
    favorites = models.IntegerField(default=0)
    category = models.ForeignKey(Category, default=1)


    def __str__(self):
        return self.question_title

class QuestionAnswer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    answer_text = models.CharField(max_length=1000)
    votes = models.IntegerField(default=0)
    favorites = models.IntegerField(default=0)


    def __str__(self):
        return self.answer_text


class UserProfile(models.Model):
    user = models.OneToOneField(User)
    address = models.CharField(max_length=100)
    phone = models.IntegerField(max_length=10)

questions/forms.py
#NOTE: refer to http://blog.narenarya.in/right-way-django-authentication.html
#I am using widgets tweaks library instead to customize django form fields using bootstrap with the tweaks library

# from django.contrib.auth.forms import AuthenticationForm
from django import forms
#
#
# # If you don't do this you cannot use Bootstrap CSS
# class LoginForm(AuthenticationForm):
#     username = forms.CharField(label="Username", max_length=30,
#                                widget=forms.TextInput(attrs={'class': 'form-control', 'name': 'username'}))
#     password = forms.CharField(label="Password", max_length=30,
#                                widget=forms.PasswordInput(attrs={'class': 'form-control', 'name': 'password'}))


class ChangePasswordForm(forms.Form):
	newpassword= forms.CharField(widget=forms.PasswordInput(attrs=dict(required=True, max_length=30)), label=("New Password"))
	renewpasssword=forms.CharField(widget=forms.PasswordInput(attrs=dict(required=True, max_length=30)), label=("Retype New Password"))


class UserRegistrationForm(forms.Form):
	username = forms.CharField(max_length=200, label=("User Name:"), required=True)
	password = forms.CharField(widget=forms.PasswordInput(attrs=dict(required=True, max_length=30)), label=("Password:"))
	fname = forms.CharField(max_length=10, label=("First Name:"), required=True)
	lname = forms.CharField(max_length=10, label=("Last Name:"), required=True)
	emailid = forms.EmailField(max_length=100, label=("Email Address:"), required=True)
	address=forms.CharField(max_length=200, widget=forms.Textarea,label=("Address:"))
	phone =forms.IntegerField(label=("Phone"))

questions/views.py
import logging

from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth.views import password_reset_confirm, password_reset
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.template import loader
from django.urls import reverse
from django.views.generic import ListView

from questions.forms import ChangePasswordForm, UserRegistrationForm
from questions.models import Question, Category, QuestionAnswer, UserProfile

logger = logging.getLogger('django')


# def index(request):
#     questions = Question.objects.all()
#     #paginator = Paginator(questions, 10)
#
#     template = loader.get_template('questions/index.html')
#     context = {
#         'questions': questions
#     }
#     return HttpResponse(template.render(context, request))

def index(request):
    # test
    question_list = Question.objects.all()
    page = request.GET.get('page', 1)

    paginator = Paginator(question_list, 10)
    try:
        questions = paginator.page(page)
    except PageNotAnInteger:
        questions = paginator.page(1)
    except EmptyPage:
        questions = paginator.page(paginator.num_pages)


    return render(request, 'questions/index.html', { 'questions': questions })


@login_required(login_url="questions/login/")
def question_form(request):
    categories = Category.objects.all()
    context = {
        'categories': categories
    }
    return render(request, 'questions/question_form.html', context)


def new_question(request):
    c = Category.objects.filter(pk=request.POST.getlist('category')[0]).get()

    q = Question(category=c,
                 question_title=request.POST['questionTitle'],
                 question_text=request.POST['questionText'])

    q.save()

    return HttpResponseRedirect(reverse('questions:index'))


def question_answers(request, question_id):
    logger.debug('question id = ' + question_id)

    question = Question.objects.get(pk=question_id)
    answers = QuestionAnswer.objects.filter(question=question)

    context = {
        'question': question,
        'answers': answers
    }

    return render(request, 'questions/question_answers.html', context)


def add_question_answer(request, question_id):
    logger.debug('an answer received for question = ' + question_id)

    question = Question.objects.get(pk=question_id)
    answer = QuestionAnswer(question=question, answer_text=request.POST['questionAnswer'])
    answer.save()

    url = reverse('questions:question_answers', kwargs={'question_id': question_id})
    return HttpResponseRedirect(url)


def vote_question(request, question_id):


    is_up = request.POST['up'] == 'true'
    is_down = request.POST['down'] == 'true'
    is_starred = request.POST['star'] == 'true'

    logger.debug('******* up = ' + str(is_up))
    logger.debug('******* down = ' + str(is_down))
    logger.debug('******* star = ' + str(is_starred))

    question = Question.objects.get(pk=question_id)

    if is_up:
        logger.debug('+1')
        question.votes += 1
    elif is_down:
        logger.debug('-1')
        question.votes -= 1
    elif is_starred:
        question.favorites += 1
    elif not is_starred:
        question.favorites -= 1

    question.save()

    answers = QuestionAnswer.objects.filter(question=question)

    context = {
        'question': question,
        'answers': answers
    }

    return render(request, 'questions/question_answers.html', context)

def vote_answer(request, question_id):
    is_up = request.POST['up'] == 'true'
    is_down = request.POST['down'] == 'true'
    is_starred = request.POST['star'] == 'true'

    question = Question.objects.get(pk=question_id)
    answer = question.questionanswer_set.filter(pk=request.POST['id']).get()

    if is_up:
        logger.debug('+1')
        answer.votes += 1
    elif is_down:
        logger.debug('-1')
        answer.votes -= 1
    elif is_starred:
        answer.favorites += 1
    elif not is_starred:
        answer.favorites -= 1

    answer.save()

    answers = QuestionAnswer.objects.filter(question=question)

    context = {
        'question': question,
        'answers': answers
    }

    return render(request, 'questions/question_answers.html', context)

@login_required
def change_password(request):
    newpassword = request.POST.get("newpassword")
    renewpasssword = request.POST.get("renewpasssword")
    username=request.user.username
    if newpassword == renewpasssword:
        if request.method == 'GET':
            form = ChangePasswordForm()
        else:
            u = User.objects.get(username__exact=username)
            u.set_password(newpassword)
            u.save()
            return redirect('/users/account')
    else:
        return redirect('/change/password/')
    return render(request,'changepassword.html', {'form': form,})

def add_user(request):
    username = request.POST.get("username")
    email = request.POST.get("emailid")
    password = request.POST.get("password")
    fname = request.POST.get("fname")
    lname = request.POST.get("lname")
    address = request.POST.get("address")
    phone = request.POST.get("phone")
    #print ".........address........",address
    if request.method == 'GET':
        form = UserRegistrationForm() #object creation
    else:
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
              user = User.objects.create_user(username, email, password)
              user.first_name = fname
              user.last_name = lname
              user.save()
              a = UserProfile(user_id=user.id,address=address,phone=phone)
              a.save()
              return redirect('questions:index')
    return render(request, 'registration.html', {'form': form,})

@login_required
def change_password(request):
    newpassword = request.POST.get("newpassword")
    renewpasssword = request.POST.get("renewpasssword")
    username=request.user.username
    if newpassword == renewpasssword:
        if request.method == 'GET':
            form = ChangePasswordForm()
        else:
            u = User.objects.get(username__exact=username)
            u.set_password(newpassword)
            u.save()
            return redirect('/login')
    else:
        return redirect('changepassword')
    return render(request, 'registration/password_change_form.html', {'form': form, })

questions/templates/questions/changepassword.html
{% include "base.html" %}

{#{% block content %}#}

<form action="{% url 'changepassword' %}" method="POST" >{% csrf_token %}
	<h1>Change Password</h1>
    <table>
    <tr><td>{{form}}</td></tr>
    <tr><td></td><td><input type="submit" value="Save Changes" />
    </td></tr>
    </table>
</form>

{#{% endblock %}#}

questions/templates/questions/footer.html
<footer class="blog-footer">
    <p>Blog template built for <a href="https://getbootstrap.com">Bootstrap</a> by <a href="https://twitter.com/mdo">@mdo</a>.
    </p>
    <p>
        <a href="#">Back to top</a>
    </p>
</footer>

questions/templates/questions/index.html
<!DOCTYPE html>
<html lang="en">
  {% include 'questions/base.html' %}

  <body>
    <div class="container">
      <div class="row">
        <div class="col-sm-8 blog-main">
          <div class="blog-post">
            <h2 class="blog-post-title" style="font-family: Chelsea Market">Most recent questions</h2>
            <p class="blog-post-meta">January 1, 2014 by <a href="#">Mark</a></p>
              <div class="container">
                  <div class="row">
                      <div class="col-md-12">
                            {% if questions %}
                                <div style="align-content: stretch; max-width: 70%">
                                <hr/>
                                {% for question in questions %}
                                    <a href="{% url 'questions:question_answers' question.id %}">{{ question.question_title }}</a> <br/>
                                    <span class="tag tag-primary">{{ question.questionanswer_set.count }} Answers</span>
                                    <span class="tag tag-primary">2 Votes</span>
                                    <span class="tag tag-info">{{ question.category.category_desc }}</span>
                                  <hr/>
                                {% endfor %}
                                </div>
                            {% endif %}

                      </div>

                  </div>
              </div>

            {% if questions.has_other_pages %}
            <nav aria-label="Page navigation">
              <ul class="pagination">
                {% if questions.has_previous %}
                  <li class="page-item">
                      <a class="page-link" aria-label="Previous" href="?page={{ questions.previous_page_number }}">
                          <span aria-hidden="true">&laquo;</span>
                          <span class="sr-only">Previous</span>
                      </a>
                  </li>
                {% else %}
                  <li class="page-item disabled">
                      <a class="page-link" href="#" aria-label="Previous">
                          <span aria-hidden="true">&laquo;</span>
                          <span class="sr-only">Previous</span>
                      </a>
                  </li>
                {% endif %}

                {% for i in questions.paginator.page_range %}
                  {% if questions.number == i %}
                    <li class="page-item">
                        <a class="page-link">
                            <span>{{ i }} <span class="sr-only">(current)</span></span>
                        </a>
                    </li>
                  {% else %}
                    <li class="page-item">
                        <a class="page-link"  href="?page={{ i }}">{{ i }}</a>
                    </li>
                  {% endif %}
                {% endfor %}

                {% if questions.has_next %}
                  <li class="page-item">
                      <a class="page-link" href="?page={{ questions.next_page_number }}" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                        <span class="sr-only">Next</span>
                      </a>
                  </li>
                {% else %}
                  <li class="page-item">
                      <a class="page-link">
                        <span>&raquo;</span>
                      </a>
                  </li>
                {% endif %}
              </ul>
            </nav>
            {% endif %}
          </div>
        </div>

        <div class="col-sm-3 offset-sm-1 blog-sidebar">
          <div class="sidebar-module sidebar-module-inset">
            <h5>Blog</h5>
            <ol class="list-unstyled">
              <li><a href="#">Spring Boot Discovery</a></li>
              <li><a href="#">JDBC Template</a></li>

            </ol>
          </div>
          <div class="sidebar-module">
            <h4>Archives</h4>
            <ol class="list-unstyled">
              <li><a href="#">March 2014</a></li>
              <li><a href="#">February 2014</a></li>
              <li><a href="#">January 2014</a></li>
              <li><a href="#">December 2013</a></li>
              <li><a href="#">November 2013</a></li>
              <li><a href="#">October 2013</a></li>
              <li><a href="#">September 2013</a></li>
              <li><a href="#">August 2013</a></li>
              <li><a href="#">July 2013</a></li>
              <li><a href="#">June 2013</a></li>
              <li><a href="#">May 2013</a></li>
              <li><a href="#">April 2013</a></li>
            </ol>
          </div>
          <div class="sidebar-module">
            <h4>Elsewhere</h4>
            <ol class="list-unstyled">
              {% if user.is_authenticated %}
              <li><a href="{% url 'questions:question_form' %}">Ask Question</a></li>
              <li><a href="{% url 'questions:changepassword' %}">Change Password</a></li>
              {% endif %}
              <li><a href="#">Twitter</a></li>
              <li><a href="#">Facebook</a></li>
            </ol>
          </div>
        </div>
      </div>
    </div>

    {% include 'questions/footer.html' %}

  </body>
</html>

questions/templates/questions/login.html
<style>
    /*
 * Specific styles of signin component
 */
/*
 * General styles
 */
body, html {
    height: 100%;
    background-repeat: no-repeat;
    background-image: linear-gradient(rgb(104, 145, 162), rgb(12, 97, 33));
}

.card-container.card {
    max-width: 350px;
    padding: 40px 40px;
}

.btn {
    font-weight: 700;
    height: 36px;
    -moz-user-select: none;
    -webkit-user-select: none;
    user-select: none;
    cursor: default;
}

/*
 * Card component
 */
.card {
    background-color: #F7F7F7;
    /* just in case there no content*/
    padding: 20px 25px 30px;
    margin: 0 auto 25px;
    margin-top: 50px;
    /* shadows and rounded borders */
    -moz-border-radius: 2px;
    -webkit-border-radius: 2px;
    border-radius: 2px;
    -moz-box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
    -webkit-box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
    box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
}

.profile-img-card {
    width: 96px;
    height: 96px;
    margin: 0 auto 10px;
    display: block;
    -moz-border-radius: 50%;
    -webkit-border-radius: 50%;
    border-radius: 50%;
}

/*
 * Form styles
 */
.profile-name-card {
    font-size: 16px;
    font-weight: bold;
    text-align: center;
    margin: 10px 0 0;
    min-height: 1em;
}

.reauth-email {
    display: block;
    color: #404040;
    line-height: 2;
    margin-bottom: 10px;
    font-size: 14px;
    text-align: center;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
    -moz-box-sizing: border-box;
    -webkit-box-sizing: border-box;
    box-sizing: border-box;
}

.form-signin #inputEmail,
.form-signin #inputPassword {
    direction: ltr;
    height: 44px;
    font-size: 16px;
}

.form-signin input[type=email],
.form-signin input[type=password],
.form-signin input[type=text],
.form-signin button {
    width: 100%;
    display: block;
    margin-bottom: 10px;
    z-index: 1;
    position: relative;
    -moz-box-sizing: border-box;
    -webkit-box-sizing: border-box;
    box-sizing: border-box;
}

.form-signin .form-control:focus {
    border-color: rgb(104, 145, 162);
    outline: 0;
    -webkit-box-shadow: inset 0 1px 1px rgba(0,0,0,.075),0 0 8px rgb(104, 145, 162);
    box-shadow: inset 0 1px 1px rgba(0,0,0,.075),0 0 8px rgb(104, 145, 162);
}

.btn.btn-signin {
    /*background-color: #4d90fe; */
    background-color: rgb(104, 145, 162);
    /* background-color: linear-gradient(rgb(104, 145, 162), rgb(12, 97, 33));*/
    padding: 0px;
    font-weight: 700;
    font-size: 14px;
    height: 36px;
    -moz-border-radius: 3px;
    -webkit-border-radius: 3px;
    border-radius: 3px;
    border: none;
    -o-transition: all 0.218s;
    -moz-transition: all 0.218s;
    -webkit-transition: all 0.218s;
    transition: all 0.218s;
}

.btn.btn-signin:hover,
.btn.btn-signin:active,
.btn.btn-signin:focus {
    background-color: rgb(12, 97, 33);
}

.forgot-password {
    color: rgb(104, 145, 162);
}

.forgot-password:hover,
.forgot-password:active,
.forgot-password:focus{
    color: rgb(12, 97, 33);
}
</style>

<!--
    you can substitue the span of reauth email for a input with the email and
    include the remember me checkbox
    -->
{#    <div class="container">#}
{#        <div class="card card-container">#}
{#            <!-- <img class="profile-img-card" src="//lh3.googleusercontent.com/-6V8xOA6M7BA/AAAAAAAAAAI/AAAAAAAAAAA/rzlHcD0KYwo/photo.jpg?sz=120" alt="" /> -->#}
{#            <img id="profile-img" class="profile-img-card" src="//ssl.gstatic.com/accounts/ui/avatar_2x.png" />#}
{#            <p id="profile-name" class="profile-name-card"></p>#}
{#            <form class="form-signin" method="post">#}
{#                {% csrf_token %}#}
{#                {{ form.as_p }}#}
{#                <span id="reauth-email" class="reauth-email"></span>#}
{#                <input type="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus>#}
{#                <input type="password" id="inputPassword" class="form-control" placeholder="Password" required>#}
{#                <div id="remember" class="checkbox">#}
{#                    <label>#}
{#                        <input type="checkbox" value="remember-me"> Remember me#}
{#                    </label>#}
{#                </div>#}
{#                <button class="btn btn-lg btn-primary btn-block btn-signin" type="submit">Sign in</button>#}
{#            </form><!-- /form -->#}
{#            <a href="#" class="forgot-password">#}
{#                Forgot the password?#}
{#            </a>#}
{#        </div><!-- /card-container -->#}
{#    </div><!-- /container -->#}


    <div class="container">
        <div class="card card-container">
            <!-- <img class="profile-img-card" src="//lh3.googleusercontent.com/-6V8xOA6M7BA/AAAAAAAAAAI/AAAAAAAAAAA/rzlHcD0KYwo/photo.jpg?sz=120" alt="" /> -->
            <img id="profile-img" class="profile-img-card" src="//ssl.gstatic.com/accounts/ui/avatar_2x.png" />
            <p id="profile-name" class="profile-name-card"></p>

            {% load i18n widget_tweaks %}

            <form class="form-signin" method="post">
                {% csrf_token %}
                {% for field in form %}
                    {% if field.errors %}
                        <div class="form-group has-error">
                            <label class="col-sm-2 control-label" for="id_{{ field.name }}">{{ field.label }}</label>
                            <div class="col-sm-10">
                                {{ field|attr:"class:form-control" }}
                                <span class="help-block">
                                    {% for error in  field.errors %}{{ error }}{% endfor %}
                                </span>
                            </div>
                        </div>
                    {% else %}
                        <div class="form-group">
                            <label class="col-sm-2 control-label" for="id_{{ field.name }}">{{ field.label }}</label>
                            <div class="col-sm-10">
                                {{ field|attr:"class:form-control"|attr:"style:height:30px" }}
                                {% if field.help_text %}
                                    <p class="help-block"><small>{{ field.help_text }}</small></p>
                                {% endif %}
                            </div>
                        </div>
                    {% endif %}
                {% endfor %}
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-primary">{% trans "Submit" %}</button>
                    </div>
                </div>
            </form>


            <a href="{% url 'reset_password_reset1' %}" class="forgot-password">
                Forgot the password?
            </a>
            <a href="{% url 'questions:add_user' %}">
                Register
            </a>
        </div><!-- /card-container -->
    </div><!-- /container -->

<script type="text/javascript">
    $( document ).ready(function() {
    // DOM ready

    // Test data
    /*
     * To test the script you should discomment the function
     * testLocalStorageData and refresh the page. The function
     * will load some test data and the loadProfile
     * will do the changes in the UI
     */
    // testLocalStorageData();
    // Load profile if it exits
    loadProfile();
});

/**
 * Function that gets the data of the profile in case
 * thar it has already saved in localstorage. Only the
 * UI will be update in case that all data is available
 *
 * A not existing key in localstorage return null
 *
 */
function getLocalProfile(callback){
    var profileImgSrc      = localStorage.getItem("PROFILE_IMG_SRC");
    var profileName        = localStorage.getItem("PROFILE_NAME");
    var profileReAuthEmail = localStorage.getItem("PROFILE_REAUTH_EMAIL");

    if(profileName !== null
            && profileReAuthEmail !== null
            && profileImgSrc !== null) {
        callback(profileImgSrc, profileName, profileReAuthEmail);
    }
}

/**
 * Main function that load the profile if exists
 * in localstorage
 */
function loadProfile() {
    if(!supportsHTML5Storage()) { return false; }
    // we have to provide to the callback the basic
    // information to set the profile
    getLocalProfile(function(profileImgSrc, profileName, profileReAuthEmail) {
        //changes in the UI
        $("#profile-img").attr("src",profileImgSrc);
        $("#profile-name").html(profileName);
        $("#reauth-email").html(profileReAuthEmail);
        $("#inputEmail").hide();
        $("#remember").hide();
    });
}

/**
 * function that checks if the browser supports HTML5
 * local storage
 *
 * @returns {boolean}
 */
function supportsHTML5Storage() {
    try {
        return 'localStorage' in window && window['localStorage'] !== null;
    } catch (e) {
        return false;
    }
}

/**
 * Test data. This data will be safe by the web app
 * in the first successful login of a auth user.
 * To Test the scripts, delete the localstorage data
 * and comment this call.
 *
 * @returns {boolean}
 */
function testLocalStorageData() {
    if(!supportsHTML5Storage()) { return false; }
    localStorage.setItem("PROFILE_IMG_SRC", "//lh3.googleusercontent.com/-6V8xOA6M7BA/AAAAAAAAAAI/AAAAAAAAAAA/rzlHcD0KYwo/photo.jpg?sz=120" );
    localStorage.setItem("PROFILE_NAME", "César Izquierdo Tello");
    localStorage.setItem("PROFILE_REAUTH_EMAIL", "oneaccount@gmail.com");
}
</script>

questions/templates/questions/question_answers.html
<html>
    {% include 'questions/base.html' %}


    <script src="/static/bower_components/tinymce/tinymce.min.js"></script>
    <script src="/static/upvote/jquery.upvote.js" type="text/javascript"></script>
    <link href="/static/upvote/jquery.upvote.css" rel="stylesheet">

    <script type="text/javascript">
        tinymce.init({
            selector: '#questionAnswer',
            theme: 'modern',
            width: 1050,
            height: 300,
            plugins: [
                'advlist autolink link image lists charmap print preview hr anchor pagebreak spellchecker',
                'searchreplace wordcount visualblocks visualchars code fullscreen insertdatetime media nonbreaking',
                'save table contextmenu directionality emoticons template paste textcolor'
            ],

            toolbar: 'undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image | print preview media fullpage | forecolor backcolor emoticons',
            relative_urls: false,
        });

        var answerCallback = function(data) {
                $.ajax({
                    url: '{% url 'questions:vote_answer' question.id %}',
                    type: 'post',
                    data: { id: data.id, up: data.upvoted, down: data.downvoted, star: data.starred, csrfmiddlewaretoken: '{{ csrf_token }}' }
                });
            };
    </script>



    <body>
        <div class="section">
            <div class="container">
                <div class="row">
                    <div class="col-md-1">
                        <div id="topic" class="upvote">
                            <a class="upvote upvote-on"></a>
                            <span class="count">{{ question.votes }}</span>
                            <a class="downvote"></a>
                            <a class="star"></a>
                        </div>
                    </div>
                    <div class="col-md-11">
                        <h3>{{ question.question_title }}</h3>
                        <hr/>

                        <div>
                            {% autoescape off %}{{ question.question_text }} {% endautoescape %}
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        {{ answers.count }} Answers
                        <hr/>
                    </div>
                </div>

                {% for answer in answers %}
                <div class="row">
                    <div class="col-md-1">
                        <div id="topic{{ answer.id }}" class="upvote">
                            <a class="upvote upvote-on"></a>
                            <span class="count">{{ answer.votes }}</span>
                            <a class="downvote"></a>
                            <a class="star"></a>
                        </div>
                        <script type="text/javascript">
                            $('#topic{{ answer.id }}').upvote({id: {{ answer.id }}, callback: answerCallback});
                        </script>
                    </div>
                    <div class="col-md-11">
                        {% autoescape off %} {{ answer.answer_text }} {% endautoescape %}
                    </div>
                </div>
                <hr/>
                {% endfor %}

                <div class="row">
                    <div class="col-md-12">
                        Your Answer
                        <form role="form" action="{% url 'questions:add_question_answer' question.id %}" method="post">
                            {% csrf_token %}
                            <textarea name="questionAnswer" id="questionAnswer"></textarea>
                            <br/>
                            <button type="submit" class="btn btn-default" contenteditable="true">Post Your Answer</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <script type="text/javascript">
            var callback = function(data) {
                $.ajax({
                    url: '{% url 'questions:vote_question' question.id %}',
                    type: 'post',
                    data: { id: data.id, up: data.upvoted, down: data.downvoted, star: data.starred, csrfmiddlewaretoken: '{{ csrf_token }}' }
                });
            };

            $('#topic').upvote({id: 123, callback: callback});

        </script>

    {% include 'questions/footer.html' %}
</body>
</html>